### ISSUE TITLE
Does not work on macOS

### ISSUE THREAD

**Issue by lauritzh** [malt3/yolo#1]
I tried to install yolo on macOS Mojava but encountered following behaviour:

```
user@laptop: sudo make install
cc yolo.c -o yolo
cp yolo /usr/bin/yolo
cp: /usr/bin/yolo: Operation not permitted
make: *** [install] Error 1
```

**Expected behaviour**:  check if installation is run on macOS, and copy yolo to `/usr/local/bin`.

**Comment by malt3** [comment]
Please read our README before opening an issue. Sadly we do not support macOS.
